Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# This should error for now.
m.plot_graph(figsize=(15,15), max_size=2400, edge_labels=True)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mMarkovError[0m                               Traceback (most recent call last)
Input [0;32mIn [24][0m, in [0;36m<module>[0;34m[0m
[1;32m      1[0m [38;5;66;03m# This should error for now.[39;00m
[0;32m----> 2[0m [43mm[49m[38;5;241;43m.[39;49m[43mplot_graph[49m[43m([49m[43mfigsize[49m[38;5;241;43m=[39;49m[43m([49m[38;5;241;43m15[39;49m[43m,[49m[38;5;241;43m15[39;49m[43m)[49m[43m,[49m[43m [49m[43mmax_size[49m[38;5;241;43m=[39;49m[38;5;241;43m2400[39;49m[43m,[49m[43m [49m[43medge_labels[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/striplog/markov.py:430[0m, in [0;36mMarkov_chain.plot_graph[0;34m(self, ax, figsize, max_size, directed, edge_labels, draw_neg)[0m
[1;32m    422[0m [38;5;28;01mdef[39;00m [38;5;21mplot_graph[39m([38;5;28mself[39m, ax[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[1;32m    423[0m                figsize[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[1;32m    424[0m                max_size[38;5;241m=[39m[38;5;241m1000[39m,
[0;32m   (...)[0m
[1;32m    427[0m                draw_neg[38;5;241m=[39m[38;5;28;01mFalse[39;00m
[1;32m    428[0m                ):
[1;32m    429[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mnormalized_difference[38;5;241m.[39mndim [38;5;241m>[39m [38;5;241m2[39m:
[0;32m--> 430[0m         [38;5;28;01mraise[39;00m MarkovError([38;5;124m"[39m[38;5;124mYou can only graph one-step chains.[39m[38;5;124m"[39m)
[1;32m    432[0m     [38;5;28;01mtry[39;00m:
[1;32m    433[0m         [38;5;28;01mimport[39;00m [38;5;21;01mnetworkx[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnx[39;00m

[0;31mMarkovError[0m: You can only graph one-step chains.
MarkovError: You can only graph one-step chains.

